### PR TITLE
BFD: Link with libiberty, libz, libdl if they are found; fixes #630

### LINKED ISSUE #630: BFD: link with libiberty
On OpenSuSE 13:
```
ralf@ark:~/symengine> make clean
ralf@ark:~/symengine> cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_BFD=yes .
ralf@ark:~/symengine> make
...
[ 54%] Building CXX object symengine/tests/rcp/CMakeFiles/test_rcp.dir/test_rcp.cpp.o
Linking CXX executable test_rcp
/usr/lib64/libbfd.a(elflink.o): In function `elf_link_add_object_symbols':
/home/abuild/rpmbuild/BUILD/binutils-2.24/build-dir/bfd/../../bfd/elflink.c:4551: undefined reference to `objalloc_free_block'
/home/abuild/rpmbuild/BUILD/binutils-2.24/build-dir/bfd/../../bfd/elflink.c:4844: undefined reference to `_sch_istable'
/usr/lib64/libbfd.a(elflink.o): In function `bfd_elf_size_dynamic_sections':
/home/abuild/rpmbuild/BUILD/binutils-2.24/build-dir/bfd/../../bfd/elflink.c:6051: undefined reference to `lbasename'
```
According to https://sourceware.org/ml/binutils/2004-02/msg00064.html and others this is due to missing `-liberty`. I'll try my hands on that if you don't mind, I need some practice with `cmake`.

EDIT. It appears libbfd does not always come with libiberty, and sometimes linking to libdl and libz is needed, so the BFD module needs a test compile to check what's needed.

### PR DESCRIPTION
**Pull request by rwst**
Just link with those libraries if they are found, and a note in readme.

### CODE REVIEW

**Comment by isuruf** [comment]
Travis test fails should be fixed in #632. (Last argument of `libfind_library` was the same earlier and we didn't detect that issue)

**Comment by rwst** [comment]
Thanks for fixing.

**Comment by certik** [comment]
I closed and reopened it to trigger another build.

**Comment by certik** [comment]
Travis now passes and Appveyor probably also passes. I restarted it in https://ci.appveyor.com/project/certik/symengine/build/303, now when #627 is merged, it should pass.

**Comment by isuruf** [comment]
+1 to merge
